# Site settings
title: Benjamin Kwon
description: Benjamin Kwon GitHub Page
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site

# User settings
username: Benjamin Kwon
user_description: Aspiring Software Engineer located in Southern California
user_title: 
email: benhkwon@gmail.com
# twitter_username: 
# github_username:  
# gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
